### PR TITLE
Add support for SQL Batch

### PR DESCRIPTION
**Pull request by BillyYccc**

### CODE REVIEW

**Comment by BillyYccc** [comment]
This will also fix #8 as it provides a basic implementation for SQL data type value mapping.

**Comment by vietj** [comment]
for data type, why not using an enum like we did for other implementations ?

**Comment by BillyYccc** [comment]
because different data types need different ways to handle column metadata(I mean their protocol definitions vary), for example, a `VARCHAR` datatype column metadata contains some extra info like `collate` to handle, so it needs to be instantiated and stored somewhere, then later used for handling rows.

**Review by vietj — APPROVED** [review]
good job

**Comment by BillyYccc** [comment]
Thanks! merging this now.

**Pull request merged**
